name: Schedule Site Rebuild
on:
  schedule:
    # UTC time that covers the range of potential executions
    - cron: '14 6-7 * * *'

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Check for correct local time (ET)
        id: time-check
        run: |
          TZ="America/New_York"
          CURRENT_HOUR=$(date +'%H')
          CURRENT_MINUTE=$(date +'%M')
          if [ "$CURRENT_HOUR" -ne "3" ] || [ "$CURRENT_MINUTE" -ne "14" ]; then
            echo "Not the correct local time. Exiting."
            exit 0
          fi

      - name: Trigger GitHub Pages rebuild
        if: ${{ success() }}  # Proceed only if the time-check step succeeds
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pages/builds
