name: Schedule Site Rebuild
on:
  schedule:
    # UTC time that covers the range of potential executions
    - cron: '14 6-7 * * 2'

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Check for correct local time (ET)
        id: time-check
        run: |
          TZ="America/New_York"
          CURRENT_HOUR=$(date +'%H')
          if [ "$CURRENT_HOUR" -ne "3" ]; then
            echo "Not the correct local time. Exiting."
            exit 0
          fi
      - name: Trigger GitHub Pages rebuild
        if: ${{ steps.time-check.outcome == 'success' }}
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pages/builds
