name: Daily Rebuild Trigger
on:
  schedule:
    - cron: '14 6-7 * * *' # Scheduled trigger
  workflow_dispatch:        # Allows manual trigger

jobs:
  rebuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main # Ensure the correct branch is checked out

      - name: Set up Git credentials
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update timestamp file
        run: |
          echo "Last rebuild: $(date)" > timestamp.txt

      - name: Commit and push changes
        run: |
          git add timestamp.txt
          if ! git diff --cached --quiet; then
            git commit -m "Automated rebuild trigger [skip ci]"
            git push origin main
          else
            echo "No changes to commit."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
