name: Schedule Site Rebuild
on:
  schedule:
    # 3:14 AM ET during standard time (7:14 UTC)
    - cron: '14 7 * * 2'
    # 3:14 AM ET during daylight saving time (6:14 UTC)
    - cron: '14 6 * * 2'

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub Pages rebuild
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pages/builds
